"""
GET /api/sites/{id}/redirect-rules

Rules are persisted between scans, so by the time they are served they are data
from storage. They still originate from scanned page content, so the endpoint
re-validates before rendering.
"""
import pytest
from fastapi.testclient import TestClient

import main


SAFE_RULES = [
    {"from": "https://acme.test/old", "to": "https://acme.test/new", "status": 301, "hops": 1},
    {"from": "https://acme.test/x", "to": "https://cdn.acme.test/y", "status": 302, "hops": 2},
]

POISONED_RULES = SAFE_RULES + [
    {"from": "https://acme.test/bad\nRedirect 301 /a /evil",
     "to": "https://acme.test/y", "status": 301, "hops": 1},
    {"from": "javascript:alert(1)", "to": "https://acme.test/y", "status": 301, "hops": 1},
]


def _client(monkeypatch, rules, snapshot=True):
    async def fake_latest(site_id):
        if not snapshot:
            return None
        return {"id": "snap-1", "created_at": "2026-07-13T00:00:00+00:00",
                "totals_json": {"redirect_rules": rules}}

    monkeypatch.setattr(main, "get_latest_snapshot", fake_latest)
    return TestClient(main.app)


@pytest.mark.parametrize("fmt,expected_name", [
    ("cloudflare", "linkspy-redirects.csv"),
    ("netlify", "_redirects"),
    ("htaccess", ".htaccess"),
])
def test_each_format_downloads_with_its_filename(monkeypatch, fmt, expected_name):
    resp = _client(monkeypatch, SAFE_RULES).get(
        "/api/sites/site-1/redirect-rules", params={"format": fmt})
    assert resp.status_code == 200
    assert expected_name in resp.headers["content-disposition"]


def test_default_format_is_cloudflare(monkeypatch):
    resp = _client(monkeypatch, SAFE_RULES).get("/api/sites/site-1/redirect-rules")
    assert resp.status_code == 200
    assert resp.text.splitlines()[0] == "source,target,status,preserve_query_string"


def test_unknown_format_is_rejected(monkeypatch):
    resp = _client(monkeypatch, SAFE_RULES).get(
        "/api/sites/site-1/redirect-rules", params={"format": "php"})
    assert resp.status_code == 400
    assert "supported" in resp.json()


@pytest.mark.parametrize("fmt", ["cloudflare", "netlify", "htaccess"])
def test_poisoned_rules_never_reach_the_artifact(monkeypatch, fmt):
    """Untrusted scanned content must not inject a directive."""
    resp = _client(monkeypatch, POISONED_RULES).get(
        "/api/sites/site-1/redirect-rules", params={"format": fmt})
    assert resp.status_code == 200
    assert "/evil" not in resp.text
    assert "javascript:" not in resp.text
    # The safe rules survive.
    assert "https://acme.test/new" in resp.text


def test_site_without_a_snapshot_returns_an_empty_ruleset(monkeypatch):
    resp = _client(monkeypatch, [], snapshot=False).get(
        "/api/sites/site-1/redirect-rules", params={"format": "netlify"})
    assert resp.status_code == 200
    assert "Generated by LinkSpy" in resp.text


def test_database_failure_returns_500(monkeypatch):
    async def boom(site_id):
        raise RuntimeError("supabase down")

    monkeypatch.setattr(main, "get_latest_snapshot", boom)
    resp = TestClient(main.app).get("/api/sites/site-1/redirect-rules")
    assert resp.status_code == 500
