"use client";

import { useState, useRef, useEffect } from "react";
import { Download, FileText, Clipboard, ChevronDown, Check } from "lucide-react";
import { LinkResult } from "@/types";

interface ExportButtonProps {
  results: LinkResult[];
  scannedUrl?: string;
  healthScore?: number;
}

const STATUS_LABELS: Record<string, string> = {
  ok: "Working",
  broken: "Page Not Found",
  redirect: "Redirected",
  blocked: "Can't Verify",
  forbidden: "Can't Verify",
  timeout: "Not Responding",
  error: "Connection Failed",
  dead_cta: "Dead Button",
};

const STATUS_NOTES: Record<string, string> = {
  ok: "",
  broken: "Remove this link or replace it with a working URL",
  redirect: "Update your link to point to the final destination URL",
  blocked: "Probably fine — this site blocks automated checkers",
  forbidden: "Probably fine — this site blocks automated checkers",
  timeout: "The site may be down or very slow",
  error: "Check for SSL issues or verify the site is online",
  dead_cta: "Add a destination URL to this button",
};

function exportCSV(results: LinkResult[]) {
  const headers = [
    "Status",
    "URL",
    "Link Text",
    "Zone",
    "Response MS",
    "Final URL",
    "Notes",
  ];
  const esc = (s: string) => `"${String(s).replace(/"/g, '""')}"`;

  const rows = results.map((r) => [
    STATUS_LABELS[r.label] ?? r.label,
    esc(r.url),
    esc(r.anchor_text),
    r.category,
    r.response_ms.toString(),
    r.final_url ? esc(r.final_url) : "",
    esc(STATUS_NOTES[r.label] ?? ""),
  ]);

  const csv = [headers.join(","), ...rows.map((row) => row.join(","))].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `link-audit-${Date.now()}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

async function exportPDF(
  results: LinkResult[],
  scannedUrl: string,
  healthScore: number
) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = 210;
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Header
  doc.setFillColor(17, 148, 120);
  doc.rect(0, 0, pageW, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Link Audit Report", margin, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated by LinkSpy  ·  ${new Date().toLocaleDateString()}`, margin, 21);
  y = 38;

  // Scanned URL
  doc.setTextColor(100, 100, 120);
  doc.setFontSize(9);
  doc.text("Scanned URL", margin, y);
  y += 5;
  doc.setTextColor(30, 30, 50);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(scannedUrl.length > 90 ? scannedUrl.slice(0, 90) + "…" : scannedUrl, margin, y);
  y += 10;

  // Health score box
  doc.setFillColor(233, 249, 245);
  doc.roundedRect(margin, y, contentW, 22, 3, 3, "F");
  doc.setTextColor(13, 110, 90);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(`${healthScore}/100`, margin + 6, y + 14);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(70, 100, 95);
  doc.text("Site Health Score", margin + 38, y + 10);

  const total = results.length;
  const broken = results.filter((r) => r.label === "broken").length;
  const dead = results.filter((r) => r.label === "dead_cta").length;
  const redirects = results.filter((r) => r.label === "redirect").length;
  doc.setFontSize(9);
  doc.text(
    `${total} links · ${broken} broken · ${dead} dead buttons · ${redirects} redirects`,
    margin + 38,
    y + 17
  );
  y += 30;

  // Table — only broken + dead_cta + redirect
  const reportRows = results.filter((r) =>
    ["broken", "dead_cta", "redirect"].includes(r.label)
  );

  if (reportRows.length === 0) {
    doc.setTextColor(80, 120, 80);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("✓ No issues found — all links are working!", margin, y + 8);
  } else {
    doc.setFillColor(17, 148, 120);
    doc.rect(margin, y, contentW, 7, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("STATUS", margin + 2, y + 4.5);
    doc.text("URL", margin + 28, y + 4.5);
    doc.text("ZONE", margin + 120, y + 4.5);
    doc.text("ACTION", margin + 148, y + 4.5);
    y += 9;

    reportRows.forEach((r, idx) => {
      if (y > 275) {
        doc.addPage();
        y = margin;
      }
      const rowBg = idx % 2 === 0 ? [250, 248, 255] : [255, 255, 255];
      doc.setFillColor(rowBg[0], rowBg[1], rowBg[2]);
      doc.rect(margin, y - 1, contentW, 9, "F");

      const statusLabel = STATUS_LABELS[r.label] ?? r.label;
      const statusColor =
        r.label === "broken" || r.label === "error"
          ? [200, 50, 50]
          : r.label === "dead_cta"
          ? [180, 130, 0]
          : [180, 90, 0];
      doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.text(statusLabel, margin + 2, y + 4.5);

      const urlTxt =
        r.url.length > 52 ? r.url.slice(0, 52) + "…" : r.url;
      doc.setTextColor(40, 40, 60);
      doc.setFont("helvetica", "normal");
      doc.text(urlTxt, margin + 28, y + 4.5);

      doc.setTextColor(100, 80, 140);
      doc.text(r.category, margin + 120, y + 4.5);

      const note = STATUS_NOTES[r.label] ?? "";
      doc.setTextColor(80, 80, 80);
      const noteTxt = note.length > 28 ? note.slice(0, 28) + "…" : note;
      doc.text(noteTxt, margin + 148, y + 4.5);

      y += 9;
    });
  }

  // Footer on each page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 180);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by LinkSpy  ·  Page ${i} of ${pageCount}`,
      pageW / 2,
      292,
      { align: "center" }
    );
  }

  doc.save(`link-audit-report-${Date.now()}.pdf`);
}

function copyToClipboard(
  results: LinkResult[],
  scannedUrl: string,
  healthScore: number
): Promise<void> {
  const total = results.length;
  const broken = results.filter((r) => r.label === "broken").length;
  const dead = results.filter((r) => r.label === "dead_cta").length;
  const redirects = results.filter((r) => r.label === "redirect").length;

  const text = [
    `Link Audit for ${scannedUrl}`,
    `Health Score: ${healthScore}/100`,
    `Total links: ${total}`,
    `Broken: ${broken}`,
    `Dead buttons: ${dead}`,
    `Redirects: ${redirects}`,
    `Checked on: ${new Date().toLocaleString()}`,
  ].join("\n");

  return navigator.clipboard.writeText(text);
}

export default function ExportButton({
  results,
  scannedUrl = "",
  healthScore = 0,
}: ExportButtonProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handler(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const handlePDF = async () => {
    setOpen(false);
    setExporting(true);
    try {
      await exportPDF(results, scannedUrl, healthScore);
    } finally {
      setExporting(false);
    }
  };

  const handleCopy = async () => {
    setOpen(false);
    await copyToClipboard(results, scannedUrl, healthScore);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const menuItemStyle = {
    fontFamily: "var(--font-poppins), Poppins, sans-serif",
    fontSize: "13px",
    fontWeight: 400,
    color: "var(--text-secondary)",
  };

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen((p) => !p)}
        className="glass-card inline-flex items-center gap-2 px-4 py-2 transition-colors cursor-pointer"
        style={{
          fontFamily: "var(--font-poppins), Poppins, sans-serif",
          fontWeight: 500,
          fontSize: "13px",
          color: "var(--text-secondary)",
        }}
        disabled={exporting}
      >
        {exporting ? (
          <span style={{ color: "var(--text-muted)" }}>Generating PDF…</span>
        ) : (
          <>
            <Download size={14} />
            Export
            <ChevronDown
              size={13}
              style={{
                transform: open ? "rotate(180deg)" : "none",
                transition: "transform 0.2s",
              }}
            />
          </>
        )}
      </button>

      {open && (
        <div
          className="absolute right-0 top-full mt-2 z-50 rounded-xl overflow-hidden flex flex-col"
          style={{
            background: "var(--surface-card)",
            border: "1px solid var(--border-subtle)",
            minWidth: "210px",
            boxShadow: "var(--elev-3)",
          }}
        >
          {/* CSV */}
          <button
            onClick={() => { exportCSV(results); setOpen(false); }}
            className="flex items-center gap-3 px-4 py-3 transition-colors cursor-pointer text-left w-full"
            style={menuItemStyle}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLButtonElement).style.background = "rgba(28,28,46,0.06)";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.background = "transparent";
            }}
          >
            <Download size={15} style={{ color: "#4caf7d" }} />
            <div>
              <div style={{ fontWeight: 500, color: "var(--text-primary)" }}>Export as CSV</div>
              <div style={{ fontSize: "11px", color: "var(--text-muted)" }}>
                All links with plain-English notes
              </div>
            </div>
          </button>

          <div style={{ height: "1px", background: "var(--border-subtle)" }} />

          {/* PDF */}
          <button
            onClick={handlePDF}
            className="flex items-center gap-3 px-4 py-3 transition-colors cursor-pointer text-left w-full"
            style={menuItemStyle}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLButtonElement).style.background = "rgba(28,28,46,0.06)";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.background = "transparent";
            }}
          >
            <FileText size={15} style={{ color: "#f5a623" }} />
            <div>
              <div style={{ fontWeight: 500, color: "var(--text-primary)" }}>Export as PDF Report</div>
              <div style={{ fontSize: "11px", color: "var(--text-muted)" }}>
                Professional report — broken links only
              </div>
            </div>
          </button>

          <div style={{ height: "1px", background: "var(--border-subtle)" }} />

          {/* Copy */}
          <button
            onClick={handleCopy}
            className="flex items-center gap-3 px-4 py-3 transition-colors cursor-pointer text-left w-full"
            style={menuItemStyle}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLButtonElement).style.background = "rgba(28,28,46,0.06)";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.background = "transparent";
            }}
          >
            {copied ? (
              <Check size={15} style={{ color: "#4caf7d" }} />
            ) : (
              <Clipboard size={15} style={{ color: "#4f46e5" }} />
            )}
            <div>
              <div style={{ fontWeight: 500, color: copied ? "#4caf7d" : "var(--text-primary)" }}>
                {copied ? "Copied!" : "Copy summary to clipboard"}
              </div>
              <div style={{ fontSize: "11px", color: "var(--text-muted)" }}>
                Plain-text audit summary
              </div>
            </div>
          </button>
        </div>
      )}
    </div>
  );
}
