// 2026 client work transcribed from the Apexure tracking sheet (Jan–June).
// Proj: [name, total, critical, medium, low, repetitive, platform]
// Del:  [name, delayDays, developer, tester]
export type Proj = [string, number, number, number, number, number, string];
export type Del = [string, number, string, string];

export const DATA: { month: string; projects: Proj[]; delivery: Del[] }[] = [
  {
    month: "2026-01",
    projects: [
      ["Social Hotspot testimonials LP", 5, 0, 0, 5, 0, "Wordpress"],
      ["BKCF Home page", 15, 0, 0, 15, 0, "website"],
      ["Lisa Marie | Experience Page", 2, 0, 0, 2, 0, "Wordpress"],
      ["Lisa Marie | Contact Page", 5, 0, 0, 5, 0, "Wordpress"],
      ["BKCF Impact page", 4, 0, 0, 4, 0, "Wordpress"],
      ["Build Competitor Website (Brand Awareness) WBI", 12, 0, 0, 12, 0, "Wordpress"],
      ["Build Radiant Floor Heating WBI", 8, 0, 0, 8, 0, "Wordpress"],
      ["Our Team Exportize page", 2, 0, 0, 2, 0, "Wordpress"],
      ["BKCF Donation Page", 5, 0, 0, 5, 0, "Wordpress"],
      ["Ahead 2026 Headway page", 2, 0, 0, 2, 0, "unbounce"],
      ["Blace | Venues Main Page", 7, 0, 0, 7, 0, "Wordpress"],
      ["BKCF Membership Page", 5, 0, 0, 5, 0, "Wordpress"],
      ["Exportize Product Subcategory Page", 5, 0, 0, 5, 0, "Wordpress"],
      ["Chorus Tim McGraw", 2, 0, 0, 2, 0, "unbounce"],
      ["Hutch | Homepage and Service Page", 10, 0, 0, 10, 0, "Webflow"],
      ["GPX Sales Page | Dr G", 15, 0, 0, 15, 0, "Wordpress"],
      ["Hutch | Industries and About Us page", 10, 0, 0, 10, 0, "Webflow"],
      ["BKCF Events Page", 8, 0, 0, 8, 0, "Wordpress"],
      ["Savvio Home Page", 10, 0, 0, 10, 0, "Webflow"],
      ["Savvio Checkout Page", 5, 0, 0, 5, 0, "Webflow"],
      ["Savvio Thank you Page", 5, 0, 0, 5, 0, "Webflow"],
      ["Savvio Security Manifesto Page", 5, 0, 0, 5, 0, "Webflow"],
      ["Savvio Pricing Page", 4, 0, 0, 4, 0, "Webflow"],
      ["Savvio Blog Page", 3, 0, 0, 3, 0, "Webflow"],
      ["Build TCC: Lead Magnet Landing Page", 12, 0, 0, 12, 0, "Hubspot"],
      ["Build Anytime Garage Door Landing Page", 10, 0, 0, 10, 0, "unbounce"],
      ["Savvio Contact Page", 3, 0, 0, 3, 0, "Webflow"],
      ["Savvio Cancel Membership Page", 1, 0, 0, 1, 0, "Webflow"],
      ["OG: Investanswers", 7, 0, 0, 7, 0, "Wordpress"],
      ["CRO Master Council Page", 12, 0, 0, 12, 0, "Wordpress"],
      ["Young The Giant Landing Page", 5, 0, 0, 5, 0, "unbounce"],
      ["Option Goddess | WP Pages", 30, 0, 0, 30, 0, "Wordpress"],
      ["Option Goddess | Podia Pages", 10, 0, 0, 10, 0, "Podia"],
      ["WBI | FAQ page", 5, 0, 0, 5, 0, "Wordpress"],
      ["Hutch | Jobs , Apply Now and Contact Us Page", 12, 0, 0, 12, 0, "Webflow"],
      ["Kashmir Bloom | Create Cashmere Throw Category", 10, 0, 0, 10, 0, "Wordpress"],
      ["TCC: Build Candidate Splash Page", 6, 0, 0, 6, 0, "Hubspot"],
      ["Build TCC: New YouTube", 10, 0, 0, 10, 0, "Hubspot"],
      ["Savvio Privacy Policy", 3, 0, 0, 3, 0, "Webflow"],
      ["Savvio Terms of Service", 2, 0, 0, 2, 0, "Webflow"],
      ["Savvio Moneyback Policy", 3, 0, 0, 3, 0, "Webflow"],
      ["Savvio Cookie Policy", 2, 0, 0, 2, 0, "Webflow"],
      ["Savvio Subsciption Terms", 2, 0, 0, 2, 0, "Webflow"],
      ["The Trading Academy Sales", 20, 0, 0, 20, 0, "GHL"],
    ],
    delivery: [
      ["Social Hotspot testimonials LP", 0, "Samiya", "Babar Shah"],
      ["BKCF Home page", 0, "Tajamul", "Anaum"],
      ["Lisa Marie | Experience Page", 0, "Arif", "Wefia"],
      ["Lisa Marie | Contact Page", 0, "Arif", "Wefia"],
      ["BKCF Impact page", 0, "Tajamul", "Babar Shah"],
      ["Build Competitor Website (Brand Awareness) WBI", 0, "Atul", "Anaum"],
      ["Build Radiant Floor Heating WBI", 0, "Atul", "Anaum"],
      ["Our Team Exportize page", 0, "Atul", "Babar Shah"],
      ["BKCF Donation Page", 0, "Tajamul", "Anaum"],
      ["Ahead 2026 Headway page", 0, "Arif", "Babar Shah"],
      ["BKCF Membership Page", 0, "Tajamul", "Anaum"],
      ["Exportize Product Subcategory Page", 0, "Atul", "Anaum"],
      ["Chorus Tim McGraw", 0, "Tajamul", "Anaum"],
      ["Blace | Venues Main Page", 0, "Viraj", "Wefia"],
      ["Hutch | Homepage and Service Page", 0, "Jaziq", "Wefia"],
      ["GPX Sales Page | Dr G", 0, "Alok", "Wefia"],
      ["Hutch | Industries and About Us page", 0, "Tajamul", "Anaum"],
      ["BKCF Events Page", 0, "Tajamul", "Anaum"],
      ["Savvio Home Page", 0, "Samiya", "Anaum"],
      ["Savvio Checkout Page", 0, "Samiya", "Anaum"],
      ["Savvio Thank you Page", 0, "Samiya", "Anaum"],
      ["Savvio Security Manifesto Page", 0, "Samiya", "Anaum"],
      ["Savvio Pricing Page", 0, "Samiya", "Anaum"],
      ["Savvio Blog Page", 0, "Samiya", "Anaum"],
      ["Build TCC: Lead Magnet Landing Page", 0, "Viraj", "Anaum"],
      ["Build Anytime Garage Door Landing Page", 0, "Tajamul", "Babar Shah"],
      ["Savvio Contact Page", 0, "Samiya", "Anaum"],
      ["Savvio Cancel Membership Page", 0, "Samiya", "Anaum"],
      ["OG: Investanswers", 0, "Atul", "Anaum"],
      ["CRO Master Council Page", 0, "Atul", "Babar Shah"],
      ["Young The Giant Landing Page", 0, "Tajamul", "Babar Shah"],
      ["Option Goddess | WP Pages", 0, "Atul", "Wefia"],
      ["Option Goddess | Podia Pages", 0, "Arif", "Wefia"],
      ["WBI | FAQ page", 0, "Atul", "Wefia"],
      ["Hutch | Jobs , Apply Now and Contact Us Page", 0, "Jaziq", "Wefia"],
      ["Kashmir Bloom | Create Cashmere Throw Category", 0, "Ifrah", "Anaum"],
      ["TCC: Build Candidate Splash Page", 0, "Samiya", "Anaum"],
      ["Build TCC: New YouTube", 0, "Samiya", "Anaum"],
      ["Savvio Privacy Policy", 0, "Samiya", "Anaum"],
      ["Savvio Terms of Service", 0, "Samiya", "Anaum"],
      ["Savvio Moneyback Policy", 0, "Samiya", "Anaum"],
      ["Savvio Cookie Policy", 0, "Samiya", "Anaum"],
      ["Savvio Subsciption Terms", 0, "Samiya", "Anaum"],
      ["The Trading Academy Sales", 0, "Jaziq", "Babar Shah"],
    ],
  },
  {
    month: "2026-02",
    projects: [
      ["Local Massachusetts Installer Valley solar Unbounce Page", 12, 0, 0, 12, 0, "Unbounce"],
      ["Fawakih FAQ's", 2, 0, 0, 2, 0, "Learnworlds"],
      ["Local Massachusetts Installer Valley solar V1 Unbounce Page", 1, 0, 0, 1, 0, "Unbounce"],
      ["Cosmetic Dental", 9, 0, 0, 9, 0, "Wordpress"],
      ["Anywhere Garage Doors", 10, 0, 0, 10, 0, "Unbounce"],
      ["Gem Revealed | Business Consulting Page", 8, 0, 0, 8, 0, "Wordpress"],
      ["Anywhere Garage Doors Installation LP", 15, 0, 0, 15, 0, "Unbounce"],
      ["TCC: Build Great Hiring Partner LP", 3, 0, 0, 3, 0, "HubSpot"],
      ["Gem Revealed | Personal coaching Page", 2, 0, 0, 2, 0, "Wordpress"],
      ["Gem Revealed | Contact Us", 6, 0, 0, 6, 0, "Wordpress"],
      ["Trustia | Homepage", 10, 0, 0, 10, 0, "Webflow"],
      ["Safe Bedding", 10, 0, 0, 10, 0, "Unbounce"],
      ["WBI | Case Studies", 9, 0, 0, 9, 0, "Wordpress"],
      ["About Us | Cyrene Labs", 8, 0, 0, 8, 0, "Wordpress"],
      ["Trading Cafe | FAQ", 6, 0, 0, 6, 0, "GHL"],
      ["Maverick | Agency 2.0", 15, 0, 0, 15, 0, "Coming Soon"],
      ["Gem Revealed | Homepage", 6, 0, 0, 6, 0, "Wordpress"],
      ["WBI: Build Our Story Page", 8, 0, 0, 8, 0, "Wordpress"],
      ["Trustia | How it works", 6, 0, 0, 6, 0, "Webflow"],
      ["Trustia | Pricing", 3, 0, 0, 3, 0, "Webflow"],
      ["Trustia | Contact Us", 2, 0, 0, 2, 0, "Webflow"],
      ["Trustia | Thank you", 2, 0, 0, 2, 0, "Webflow"],
      ["Trustia | Security Manifesto", 2, 0, 0, 2, 0, "Webflow"],
      ["Trustia | Cancel my subscription", 1, 0, 0, 1, 0, "Webflow"],
      ["Apexure | About us", 5, 0, 0, 5, 0, "Webflow"],
      ["Apexure | CRO", 10, 0, 0, 10, 0, "Webflow"],
      ["Apexure | PPC", 10, 0, 0, 10, 0, "Webflow"],
      ["Apexure | Homepage", 15, 0, 0, 15, 0, "Webflow"],
      ["Apexure | Chiropractic Landing Page", 20, 0, 0, 20, 0, "Webflow"],
      ["Apexure | Advertorial Landing Page", 10, 0, 0, 10, 0, "Webflow"],
      ["Apexure | Conversion Websites", 10, 0, 0, 10, 0, "Webflow"],
      ["Apexure | SaaS Landing Page", 7, 0, 0, 7, 0, "Webflow"],
      ["Apexure | Contact us", 3, 0, 0, 3, 0, "Webflow"],
      ["Safety Minds | Lp", 2, 0, 0, 2, 0, "Wordpress"],
      ["BKCF | Member", 2, 0, 0, 2, 0, "Wordpress"],
    ],
    delivery: [
      ["Local Massachusetts Installer Valley solar Unbounce Page", 0, "Jaziq", "Babar Shah"],
      ["Fawakih FAQ's", 0, "Tajamul", "Babar Shah"],
      ["Local Massachusetts Installer Valley solar V1 Unbounce Page", 0, "Arif", "Babar Shah"],
      ["Cosmetic Dental", 0, "Viraj", "Babar Shah"],
      ["Anywhere Garage Doors", 0, "Tajamul", "Babar Shah"],
      ["Gem Revealed | Business Consulting Page", 0, "Viraj", "Babar Shah"],
      ["Anywhere Garage Doors Installation LP", 0, "Jaziq", "Anaum"],
      ["TCC: Build Great Hiring Partner LP", 0, "Tajamul", "Anaum"],
      ["Gem Revealed | Personal coaching Page", 0, "Viraj", "Babar Shah"],
      ["Gem Revealed | Contact Us", 0, "Viraj", "Babar Shah"],
      ["Trustia | Homepage", 0, "Arif", "Anaum"],
      ["Safe Bedding", 0, "Samiya", "Wefia"],
      ["WBI | Case Studies", 0, "Atul", "Wefia"],
      ["About Us | Cyrene Labs", 0, "Alok", "Wefia"],
      ["Trading Cafe | FAQ", 0, "Jaziq", "Wefia"],
      ["Maverick | Agency 2.0", 0, "Atul", "Wefia"],
      ["Gem Revealed | Homepage", 0, "Viraj", "Babar Shah"],
      ["WBI: Build Our Story Page", 0, "Atul", "Babar Shah"],
      ["Trustia | How it works", 0, "Arif", "Anaum"],
      ["Trustia | Pricing", 0, "Arif", "Anaum"],
      ["Trustia | Contact Us", 0, "Arif", "Anaum"],
      ["Trustia | Thank you", 0, "Arif", "Anaum"],
      ["Trustia | Security Manifesto", 0, "Arif", "Anaum"],
      ["Trustia | Cancel my subscription", 0, "Ifrah", "Anaum"],
      ["Apexure | About us", 0, "Ifrah", "Anaum"],
      ["Apexure | CRO", 0, "Ifrah", "Anaum"],
      ["Apexure | PPC", 0, "Ifrah", "Anaum"],
      ["Apexure | Homepage", 0, "Ifrah", "Anaum"],
      ["Apexure | Chiropractic Landing Page", 0, "Ifrah", "Anaum"],
      ["Apexure | Advertorial Landing Page", 0, "Ifrah", "Anaum"],
      ["Apexure | Conversion Websites", 0, "Ifrah", "Anaum"],
      ["Apexure | SaaS Landing Page", 0, "Ifrah", "Anaum"],
      ["Apexure | Contact us", 0, "Ifrah", "Anaum"],
      ["Safety Minds | Lp", 0, "Viraj", "Wefia"],
      ["BKCF | Member", 0, "Tajamul", "Anaum"],
    ],
  },
  {
    month: "2026-03",
    projects: [
      ["DR G Homepage", 15, 0, 0, 15, 0, "wordpress"],
      ["U S Patriot Insurance page", 6, 0, 0, 6, 0, "wordpress"],
      ["Build RateHounds Page | Forge 47", 10, 0, 0, 10, 0, "Elementor"],
      ["Build Support Page", 5, 0, 0, 5, 0, "Kajabi"],
      ["DR G Booking Page", 10, 0, 0, 10, 0, "wordpress"],
      ["DR G Community Page", 7, 0, 0, 7, 0, "wordpress"],
      ["Updater: Create Test Variant | Cox Cables", 3, 0, 0, 3, 0, "Swipepages"],
      ["House of Rufus | Chorus", 8, 0, 0, 8, 0, "Unbounce"],
      ["OG Academy Courses Main Page", 12, 0, 0, 12, 0, "Kajabi"],
      ["OG Academy Courses Single Page", 8, 0, 0, 8, 0, "Kajabi"],
      ["The Trading Cafe | Legacy Program", 15, 0, 0, 15, 0, "GHL"],
      ["Econes Drilllight | Agency 2.0", 17, 0, 0, 17, 0, "Elementor"],
      ["DR G FAQ's", 2, 0, 0, 2, 0, "wordpress"],
      ["WBI Blog", 7, 0, 0, 7, 0, "wordpress"],
      ["WBI Our team", 7, 0, 0, 7, 0, "wordpress"],
      ["Health Insurance | Forge 47", 5, 0, 0, 5, 0, "wordpress"],
      ["DR G contact us page", 3, 0, 0, 3, 0, "wordpress"],
      ["The Coherence Coach", 9, 0, 0, 9, 0, "GHL"],
      ["GHP Call Schedule Pages", 5, 0, 0, 5, 0, "Hubspot"],
      ["APH: Savvio Acquisition Landing (Reuse Shopping Protection LP)", 7, 0, 0, 7, 0, "wordpress"],
      ["Refer a Friend | Landing Page Build | Wordpress", 4, 0, 0, 4, 0, "wordpress"],
      ["WBI | Radiant Panels LP", 10, 0, 0, 10, 0, "wordpress"],
      ["OG | Courses Dashboard", 12, 0, 0, 12, 0, "Kajabi"],
      ["Agency 2.0 Coming soon Main page", 15, 0, 0, 15, 0, "wordpress"],
      ["Agency 2.0 Coming soon Reservation page", 5, 0, 0, 5, 0, "wordpress"],
      ["Agency 2.0 Coming soon Thank you page", 2, 0, 0, 2, 0, "wordpress"],
      ["DR G About us page", 1, 0, 0, 1, 0, "wordpress"],
      ["Ahead 2026 headway LP", 5, 0, 0, 5, 0, "Unbounce"],
      ["Chicken Dinner", 15, 0, 0, 15, 0, "Unbounce"],
      ["24 Hours AR Hubspot LP", 22, 0, 0, 22, 0, "Hubspot"],
      ["SEO Ratehounds", 3, 0, 0, 3, 0, "wordpress"],
      ["General Radiant Heat LP WBI", 8, 0, 0, 8, 0, "wordpress"],
      ["SideKick Comingsoon", 20, 0, 0, 20, 0, "wordpress"],
      ["5-Day Metabolic Health | Dr Steven G", 8, 0, 0, 8, 0, "Kajabi"],
      ["F47: Build Anystate Insurance Page", 9, 0, 0, 9, 0, "wordpress"],
      ["Build | Special Needs Trust Hub Page", 8, 0, 0, 8, 0, "wordpress"],
      ["Build Hydronic Heating LP", 7, 0, 0, 7, 0, "wordpress"],
      ["Alan Parsons Newsletter Landing Page", 2, 0, 0, 2, 0, "Unbounce"],
      ["DR G overdrive supplement GPX page", 15, 0, 0, 15, 0, "wordpress"],
    ],
    delivery: [
      ["DR G Homepage", 0, "Viraj", "Babar Shah"],
      ["U S Patriot Insurance page", 0, "Jaziq", "Babar Shah"],
      ["Build RateHounds Page | Forge 47", 0, "Samiya", "Anaum"],
      ["Build Support Page", 0, "Arif", "Anaum"],
      ["DR G Booking Page", 0, "Viraj", "Babar Shah"],
      ["DR G Community Page", 0, "Viraj", "Babar Shah"],
      ["Updater: Create Test Variant | Cox Cables", 0, "Tajamul", "Anaum"],
      ["House of Rufus | Chorus", 0, "Tajamul", "Wefia"],
      ["OG Academy Courses Main Page", 0, "Alok", "Wefia"],
      ["OG Academy Courses Single Page", 0, "Alok", "Wefia"],
      ["The Trading Cafe | Legacy Program", 0, "Samiya", "Wefia"],
      ["Econes Drilllight | Agency 2.0", 0, "Jaziq", "Wefia"],
      ["DR G FAQ's", 0, "Viraj", "Babar Shah"],
      ["WBI Blog", 0, "Atul", "Anaum"],
      ["WBI Our team", 0, "Atul", "Anaum"],
      ["Health Insurance | Forge 47", 0, "Samiya", "Anaum"],
      ["DR G contact us page", 0, "Viraj", "Babar Shah"],
      ["The Coherence Coach", 0, "Arif", "Wefia"],
      ["GHP Call Schedule Pages", 0, "Tajamul", "Anaum"],
      ["APH: Savvio Acquisition Landing (Reuse Shopping Protection LP)", 0, "Samiya", "Anaum"],
      ["Refer a Friend | Landing Page Build | Wordpress", 0, "Jaziq", "Anaum"],
      ["WBI | Radiant Panels LP", 0, "Atul", "Wefia"],
      ["OG | Courses Dashboard", 0, "Alok", "Tajamul"],
      ["Agency 2.0 Coming soon Main page", 0, "Atul", "Anaum"],
      ["Agency 2.0 Coming soon Reservation page", 0, "Atul", "Anaum"],
      ["Agency 2.0 Coming soon Thank you page", 0, "Atul", "Anaum"],
      ["DR G About us page", 0, "Viraj", "Babar Shah"],
      ["Ahead 2026 headway LP", 0, "Arif", "Babar Shah"],
      ["Chicken Dinner", 0, "Tajamul", "Wefia"],
      ["24 Hours AR Hubspot LP", 0, "Samiya", "Babar Shah"],
      ["SEO Ratehounds", 0, "Samiya", "Babar Shah"],
      ["General Radiant Heat LP WBI", 0, "Atul", "Babar Shah"],
      ["SideKick Comingsoon", 0, "Jaziq", "Babar Shah"],
      ["5-Day Metabolic Health | Dr Steven G", 0, "Atul", "Wefia"],
      ["F47: Build Anystate Insurance Page", 0, "Samiya", "Anaum"],
      ["Build | Special Needs Trust Hub Page", 0, "Arif", "Anaum"],
      ["Build Hydronic Heating LP", 0, "Atul", "Anaum"],
      ["Alan Parsons Newsletter Landing Page", 0, "Atul", "Anaum"],
      ["DR G overdrive supplement GPX page", 0, "Viraj", "Babar Shah"],
    ],
  },
  {
    month: "2026-04",
    projects: [
      ["WBI Branded LP", 10, 0, 0, 10, 0, "wordpress"],
      ["Elite Practice", 10, 0, 0, 10, 0, "Clickfunnel"],
      ["Lawsuit Winners", 20, 0, 0, 20, 0, "wordpress"],
      ["T4Media | Hubspot Page", 11, 0, 0, 11, 0, "Hubspot"],
      ["DR G Defence Mode GPX page", 4, 0, 0, 4, 0, "wordpress"],
      ["DR G Gut Mode GPX page", 2, 0, 0, 2, 0, "wordpress"],
      ["DR G Anti-inflammatory GPX page", 6, 0, 0, 6, 0, "wordpress"],
      ["DR G Energy Boost GPX page", 4, 0, 0, 4, 0, "wordpress"],
      ["DR G Product Active B12 GPX page", 4, 0, 0, 4, 0, "wordpress"],
      ["DR G Product overdrive GPX Quiz page", 1, 0, 0, 1, 0, "wordpress"],
      ["Care First Headway LP", 4, 0, 0, 4, 0, "unbounce"],
      ["WBI Pmax", 10, 0, 0, 10, 0, "Wordpress"],
      ["Cookie Finance", 13, 0, 0, 13, 0, "Hubspot"],
      ["DR G Defence Mode GPX Quiz page", 2, 0, 0, 2, 0, "Wordpress"],
      ["DR G Gut check GPX Quiz page", 1, 0, 0, 1, 0, "Wordpress"],
      ["DR G Recharged GPX Quiz page", 1, 0, 0, 1, 0, "Wordpress"],
      ["DR G Cool down GPX Quiz page", 0, 0, 0, 0, 0, "Wordpress"],
      ["DR G Free Resource page", 2, 0, 0, 2, 0, "Wordpress"],
      ["Study-specific Radical science LP", 6, 0, 0, 6, 0, "Hubspot"],
      ["Build | Tubing and Manifolds", 8, 0, 0, 8, 0, "Wordpress"],
      ["Build | Mechanical System & Design", 8, 0, 0, 8, 0, "Wordpress"],
      ["Build | Funnel 2 Landing Page", 12, 0, 0, 12, 0, "Clickfunnel"],
      ["Affiliate Page Build | Hubspot | Cookie Finance", 12, 0, 0, 12, 0, "Hubspot"],
      ["Build | Funnel 4 Landing Page", 8, 0, 0, 8, 0, "Clickfunnel"],
      ["Build | Funnel 3 Landing Page", 14, 0, 0, 14, 0, "Clickfunnel"],
      ["Payroll calculator page hutch", 4, 0, 0, 4, 0, "webflow"],
      ["Sandra Network | Industries Pages", 18, 0, 0, 18, 0, "Wordpress"],
      ["Bindscout lp", 7, 0, 0, 7, 0, "Wordpress"],
      ["Shopping care | APH", 20, 0, 0, 20, 0, "Elementor"],
      ["Shopping care | Pricing", 6, 0, 0, 6, 0, "Elementor"],
      ["Shopping care | Core Features", 4, 0, 0, 4, 0, "Elementor"],
      ["Shopping care | Contact", 8, 0, 0, 8, 0, "Elementor"],
      ["Bindscout SEO Template lp", 0, 0, 0, 0, 0, "Wordpress"],
      ["Surpass Industrial | Landing Page", 15, 0, 0, 15, 0, "Wix"],
      ["THE 7-DAY PROVIDER CHALLENGE Trading cafe", 13, 0, 0, 13, 0, "GHL"],
      ["Practitioner Resources cyrene labs", 10, 0, 0, 10, 0, "Wordpress"],
      ["LLUM | Landing Page Build | Hubspot", 18, 0, 0, 18, 0, "Hubspot"],
      ["Talk to panel expert | WBI", 8, 0, 0, 8, 0, "Wordpress"],
      ["request a sample | WBI", 4, 0, 0, 4, 0, "Wordpress"],
      ["Sandra Network | Website Pages", 35, 0, 0, 35, 0, "Wordpress"],
      ["Build | Mister Roof Repair LP", 15, 0, 0, 15, 0, "Unbounce"],
      ["student results | the trading cafe", 8, 0, 0, 8, 0, "GHL"],
    ],
    delivery: [
      ["WBI Branded LP", 0, "Atul", "Babar Shah"],
      ["Elite Practice", 0, "Tajamul", "Anaum"],
      ["Lawsuit Winners", 0, "Jaziq", "Babar Shah"],
      ["T4Media | Hubspot Page", 0, "Samiya", "Wefia"],
      ["DR G Defence Mode GPX page", 0, "Viraj", "Babar Shah"],
      ["DR G Gut Mode GPX page", 0, "Viraj", "Babar Shah"],
      ["DR G Anti-inflammatory GPX page", 0, "Viraj", "Babar Shah"],
      ["DR G Energy Boost GPX page", 0, "Viraj", "Babar Shah"],
      ["DR G Product Active B12 GPX page", 0, "Viraj", "Babar Shah"],
      ["DR G Product overdrive GPX Quiz page", 0, "Viraj", "Babar Shah"],
      ["Care First Headway LP", 0, "Arif", "Babar Shah"],
      ["WBI Pmax", 0, "Atul", "Anaum"],
      ["Cookie Finance", 0, "Samiya", "Anaum"],
      ["DR G Defence Mode GPX Quiz page", 0, "Viraj", "Babar Shah"],
      ["DR G Gut check GPX Quiz page", 0, "Viraj", "Babar Shah"],
      ["DR G Recharged GPX Quiz page", 0, "Viraj", "Babar Shah"],
      ["DR G Cool down GPX Quiz page", 0, "Viraj", "Babar Shah"],
      ["DR G Free Resource page", 0, "Viraj", "Babar Shah"],
      ["Study-specific Radical science LP", 0, "Samiya", "Babar Shah"],
      ["Build | Tubing and Manifolds", 0, "Atul", "Anaum"],
      ["Build | Mechanical System & Design", 0, "Atul", "Anaum"],
      ["Build | Funnel 2 Landing Page", 0, "Tajamul", "Anaum"],
      ["Affiliate Page Build | Hubspot | Cookie Finance", 0, "Samiya", "Anaum"],
      ["Build | Funnel 4 Landing Page", 0, "Tajamul", "Anaum"],
      ["Build | Funnel 3 Landing Page", 0, "Tajamul", "Anaum"],
      ["Payroll calculator page hutch", 0, "Arif", "Babar Shah"],
      ["Bindscout lp", 0, "Samiya", "Babar Shah"],
      ["Shopping care | APH", 0, "Alok", "Anaum"],
      ["Shopping care | Pricing", 0, "Samiya", "Anaum"],
      ["Shopping care | Core Features", 0, "Samiya", "Anaum"],
      ["Shopping care | Contact", 0, "Samiya", "Anaum"],
      ["Bindscout SEO Template lp", 0, "Samiya", "Babar Shah"],
      ["Sandra Network | Industries Pages", 0, "Jaziq", "Anaum"],
      ["Surpass Industrial | Landing Page", 0, "Tajamul", "Babar Shah"],
      ["THE 7-DAY PROVIDER CHALLENGE Trading cafe", 0, "Arif", "Babar Shah"],
      ["Practitioner Resources cyrene labs", 0, "Atul", "Babar Shah"],
      ["LLUM | Landing Page Build | Hubspot", 0, "Jaziq", "Anaum"],
      ["Talk to panel expert | WBI", 0, "Atul", "Anaum"],
      ["request a sample | WBI", 0, "Atul", "Anaum"],
      ["Sandra Network | Website Pages", 0, "Jaziq", "Wefia"],
      ["student results | the trading cafe", 0, "Tajamul", "Anaum"],
      ["Build | Mister Roof Repair LP", 0, "Arif", "Anaum"],
    ],
  },
  {
    month: "2026-05",
    projects: [
      ["Student Results LP Trading cafe", 9, 0, 0, 9, 0, "GHL"],
      ["The Quick Win Program Trading Cafe", 6, 0, 0, 6, 0, "GHL"],
      ["My ACA guide", 2, 0, 0, 2, 0, "Wordpress"],
      ["Brown electric form lp", 4, 0, 0, 4, 0, "Wordpress"],
      ["Invitation To Join The Trading Academy", 7, 0, 0, 7, 0, "GHL"],
      ["Opt in funnel trading cafe", 8, 0, 0, 8, 0, "GHL"],
      ["Sandra network website", 30, 0, 0, 30, 0, "Wordpress"],
      ["Build Canadian Landing Page (Sub-Directory)", 12, 0, 0, 12, 0, "Wordpress"],
      ["Build Canadian Landing Page", 10, 0, 0, 10, 0, "Wordpress"],
      ["Savvio Quiz Funnel Integration", 2, 0, 0, 2, 0, "webflow"],
      ["Invitation To Join The Trading Academy Updated", 9, 0, 0, 9, 0, "GHL"],
      ["LLUM | 2nd LP | Construction Companies", 18, 0, 0, 18, 0, "Hubspot"],
      ["Elite practice Beyond clinical experience", 12, 0, 0, 12, 0, "Clickfunnel"],
      ["Opt-In | Funnel trading cafe", 2, 0, 0, 2, 0, "GHL"],
      ["Suppliment provider Cyrene labs", 10, 0, 0, 10, 0, "Wordpress"],
      ["Peak Financial Planning", 2, 0, 0, 2, 0, "Hubspot"],
      ["TCC: Update HVAC and Electrical Google LPs", 7, 0, 0, 7, 0, "Wordpress"],
      ["Build Hydronic Heat Overview page", 8, 0, 0, 8, 0, "Hubspot"],
      ["Savvio Skill-Based Quiz Contest", 1, 0, 0, 1, 0, "Webflow"],
      ["Updater poweredby", 8, 0, 0, 8, 0, "Swipepages"],
      ["Confirmation page Trading Cafe", 2, 0, 0, 2, 0, "GHL"],
      ["Join The Academy Trading cafe", 3, 0, 0, 3, 0, "GHL"],
      ["While you wait Trading cafe", 2, 0, 0, 2, 0, "GHL"],
      ["Early Bird Confirmation Trading cafe", 3, 0, 0, 3, 0, "GHL"],
      ["Build | 7-Day Retirement Plan Trading cafe", 20, 0, 0, 20, 0, "GHL"],
      ["RhinoCo | Landing Page", 8, 0, 0, 8, 0, "webflow"],
      ["Segments fawakih Landing Page", 5, 0, 0, 5, 0, "Learnworlds"],
      ["Anystate insurence CALL ONLY forge47", 3, 0, 0, 3, 0, "wordpress"],
      ["Contact us The Trading Cafe page website", 4, 0, 0, 4, 0, "GHL"],
      ["Build | Cafe live Event Funnel", 10, 0, 0, 10, 0, "GHL"],
      ["Build Remodel page | WBI", 10, 0, 0, 10, 0, "wordpress"],
      ["Resource The Trading Cafe page website", 2, 0, 0, 2, 0, "GHL"],
      ["FAQ'S The Trading Cafe page website", 4, 0, 0, 4, 0, "GHL"],
      ["About us The Trading Cafe page website", 6, 0, 0, 6, 0, "GHL"],
      ["AO Cohort Schedule Landing Page fawakih", 3, 0, 0, 3, 0, "Learnworlds"],
      ["Ahead 2026 LP updates", 4, 0, 0, 4, 0, "unbounce"],
      ["Bindscout | Agent page", 1, 0, 0, 1, 0, "Wordpress"],
      ["Build LVP & LVT Page", 7, 0, 0, 7, 0, "Wordpress"],
    ],
    delivery: [
      ["Student Results LP Trading cafe", 0, "Samiya", "Babar Shah"],
      ["The Quick Win Program Trading Cafe", 0, "Tajamul", "Babar Shah"],
      ["My ACA guide", 0, "Atul", "Babar Shah"],
      ["Brown electric form lp", 0, "Arif", "Babar Shah"],
      ["Invitation To Join The Trading Academy", 0, "Samiya", "Babar Shah"],
      ["Opt in funnel trading cafe", 0, "Samiya", "Babar Shah"],
      ["Sandra network website", 0, "Jaziq", "Anaum"],
      ["Build Canadian Landing Page (Sub-Directory)", 0, "Atul", "Anaum"],
      ["Build Canadian Landing Page", 0, "Atul", "Anaum"],
      ["Savvio Quiz Funnel Integration", 0, "Viraj", "Babar Shah"],
      ["Invitation To Join The Trading Academy Updated", 0, "Samiya", "Babar Shah"],
      ["LLUM | 2nd LP | Construction Companies", 0, "Alok", "Babar Shah"],
      ["Elite practice Beyond clinical experience", 0, "Arif", "Anaum"],
      ["Opt-In | Funnel trading cafe", 0, "Samiya", "Babar Shah"],
      ["Suppliment provider Cyrene labs", 0, "Alok", "Babar Shah"],
      ["Peak Financial Planning", 0, "Arif", "Babar Shah"],
      ["TCC: Update HVAC and Electrical Google LPs", 0, "Samiya", "Anaum"],
      ["Build Hydronic Heat Overview page", 0, "Atul", "Anaum"],
      ["Savvio Skill-Based Quiz Contest", 0, "Viraj", "Babar Shah"],
      ["Updater poweredby", 0, "Arif", "Babar Shah"],
      ["Confirmation page Trading Cafe", 0, "Samiya", "Babar Shah"],
      ["Join The Academy Trading cafe", 0, "Samiya", "Babar Shah"],
      ["While you wait Trading cafe", 0, "Samiya", "Babar Shah"],
      ["Early Bird Confirmation Trading cafe", 0, "Tajamul", "Babar Shah"],
      ["Build | 7-Day Retirement Plan Trading cafe", 0, "Tajamul", "Anaum"],
      ["RhinoCo | Landing Page", 0, "Arif", "Babar Shah"],
      ["Segments fawakih Landing Page", 0, "Tajamul", "Babar Shah"],
      ["Anystate insurence CALL ONLY forge47", 0, "Samiya", "Babar Shah"],
      ["Contact us The Trading Cafe page website", 0, "Samiya", "Babar Shah"],
      ["Build | Cafe live Event Funnel", 0, "Tajamul", "Anaum"],
      ["Build Remodel page | WBI", 0, "Atul", "Anaum"],
      ["Resource The Trading Cafe page website", 0, "Samiya", "Babar Shah"],
      ["FAQ'S The Trading Cafe page website", 0, "Tajamul", "Babar Shah"],
      ["About us The Trading Cafe page website", 0, "Samiya", "Babar Shah"],
      ["AO Cohort Schedule Landing Page fawakih", 0, "Viraj", "Babar Shah"],
      ["Ahead 2026 LP updates", 0, "Arif", "Babar Shah"],
      ["Bindscout | Agent page", 0, "Samiya", "Babar Shah"],
      ["Build LVP & LVT Page", 0, "Atul", "Anaum"],
    ],
  },
  {
    month: "2026-06",
    projects: [
      ["Laurier Dental Spa", 25, 0, 0, 25, 25, "clickfunnel"],
      ["Kardynal acquisition new lp", 7, 0, 0, 7, 0, "webflow"],
      ["Dr. Bashi's landing page", 13, 0, 0, 13, 0, "clickfunnel"],
      ["Instructor Individual - Arabic Online", 4, 0, 0, 4, 0, "GHL"],
      ["New Homepage Trading cafe", 5, 0, 0, 5, 0, "Unbounce"],
      ["Cannons FAQ page", 5, 0, 0, 5, 0, "Hubspot"],
      ["LLUM | Build | 3rd Landing Page", 9, 0, 0, 9, 0, "Wordpress"],
      ["Build | Request an estimate Page", 12, 0, 0, 12, 0, "Wordpress"],
      ["Build | Order Now page", 15, 0, 0, 15, 0, "GHL"],
      ["Build Funnel | The Foundation Program", 8, 0, 0, 8, 0, "GHL"],
      ["New Quick Win Page | Adjustments", 9, 0, 0, 9, 0, "GHL"],
      ["Arabic Online: Monthly vs Yearly", 5, 0, 0, 5, 0, "Learnworlds"],
      ["High School Landing Page | Fawakih", 0, 0, 0, 0, 0, "Learnworlds"],
      ["Build | Dr Bashi's Landing Page | Multiple Missing Teeth", 10, 0, 0, 10, 0, "clickfunnel"],
      ["Build | inspirelifepartners", 10, 0, 0, 10, 0, "Wordpress"],
    ],
    delivery: [
      ["Laurier Dental Spa", 0, "Alok", "Babar Shah"],
      ["Kardynal acquisition new lp", 0, "Samiya", "Babar Shah"],
      ["Dr. Bashi's landing page", 0, "Tajamul", "Babar Shah"],
      ["Instructor Individual - Arabic Online", 0, "Viraj", "Babar Shah"],
      ["New Homepage Trading cafe", 0, "Tajamul", "Anaum"],
      ["Cannons FAQ page", 0, "Junaid", "Anaum"],
      ["LLUM | Build | 3rd Landing Page", 0, "Arif", "Anaum"],
      ["Build | Request an estimate Page", 0, "Atul", "Anaum"],
      ["Build | Order Now page", 0, "Atul", "Anaum"],
      ["Build Funnel | The Foundation Program", 0, "Tajamul", "Anaum"],
      ["New Quick Win Page | Adjustments", 0, "Samiya", "Anaum"],
      ["Arabic Online: Monthly vs Yearly", 0, "Viraj", "Anaum"],
      ["High School Landing Page | Fawakih", 0, "Arif", "Babar Shah"],
      ["Build | Dr Bashi's Landing Page | Multiple Missing Teeth", 0, "Tajamul", "Anaum"],
      ["Build | inspirelifepartners", 0, "Atul", "Anaum"],
    ],
  },
];
