import { test } from "node:test";
import assert from "node:assert/strict";
import { liveSocketUrl, signLiveToken, TOKEN_TTL_S } from "@/lib/devicepreview/live-token";

// Generated by services/devicepreview/live.py with these exact inputs. If this
// fails, the two implementations have drifted and every session will be
// refused as unauthorized — which is a confusing way to find out.
const SECRET = "test-service-key-0123456789";
const URL_ = "https://breezioac.com/lp/";
const PROFILE = "galaxy-s25";
const AT_MS = 1_757_000_000_000;
const FROM_PYTHON =
  "eyJleHAiOjE3NTcwMDAxMjAsInByb2ZpbGUiOiJnYWxheHktczI1IiwidXJsIjoiaHR0cHM6Ly9icmVlemlvYWMuY29tL2xwLyJ9" +
  ".1a1ca31cf20c35c9e92b333b8f184c682a776d20069bf997ac4428c1703e0748";

test("a minted token is byte-for-byte what the service will accept", () => {
  assert.equal(signLiveToken(SECRET, URL_, PROFILE, AT_MS), FROM_PYTHON);
});

test("the payload is base64url with no padding, and decodes to sorted compact JSON", () => {
  const [body] = FROM_PYTHON.split(".");
  assert.doesNotMatch(body, /[+/=]/, "base64url, unpadded");
  const json = Buffer.from(body, "base64url").toString("utf8");
  assert.equal(json, `{"exp":1757000120,"profile":"galaxy-s25","url":"https://breezioac.com/lp/"}`);
});

test("the expiry is the ttl the service expects", () => {
  const [body] = signLiveToken(SECRET, URL_, PROFILE, AT_MS).split(".");
  const { exp } = JSON.parse(Buffer.from(body, "base64url").toString("utf8"));
  assert.equal(exp - Math.floor(AT_MS / 1000), TOKEN_TTL_S);
});

test("a different url, profile, key or minute is a different token", () => {
  const base = signLiveToken(SECRET, URL_, PROFILE, AT_MS);
  assert.notEqual(signLiveToken(SECRET, "https://example.com/", PROFILE, AT_MS), base);
  assert.notEqual(signLiveToken(SECRET, URL_, "iphone-16", AT_MS), base);
  assert.notEqual(signLiveToken("another-key", URL_, PROFILE, AT_MS), base);
  assert.notEqual(signLiveToken(SECRET, URL_, PROFILE, AT_MS + 60_000), base);
});

test("the socket url points at the service over wss, carrying the token", () => {
  assert.equal(
    liveSocketUrl("https://devicepreview.up.railway.app", "abc.def"),
    "wss://devicepreview.up.railway.app/api/devicepreview/live-session?token=abc.def",
  );
  assert.match(liveSocketUrl("http://localhost:8000/", "t"), /^ws:\/\/localhost:8000\//,
    "plain http stays plain ws, for a local service");
  assert.match(liveSocketUrl("https://x.app", "a+b/c=d"), /token=a%2Bb%2Fc%3Dd$/,
    "the token is escaped, not pasted");
});
