import { createHmac, randomBytes } from "node:crypto";

// The live-session token, minted here and read by services/devicepreview/live.py.
//
// Deliberately not "server-only": the secret is an argument, not a module
// constant, so there is nothing here to leak and the signing can be unit
// tested against the Python implementation. The route that calls it is the
// piece that reads the key from the environment.
//
// The browser cannot hold the service key, so this is what stands between a
// page and the service. It PINS the url and the profile: the service reads
// both from the token and never from the query string, so a token that leaks
// opens exactly one page on one profile until it expires, and can never be
// used to browse the service somewhere else.
//
// The two implementations must agree byte for byte, so the shape is fixed:
// compact JSON with its keys sorted, base64url with the padding stripped, a
// dot, and a lowercase hex HMAC-SHA256 of everything before the dot. The unit
// test pins a token generated by the Python side against these exact inputs.

/** Must match SESSION_TTL_S in live.py. Long enough to open a session, no more. */
export const TOKEN_TTL_S = 120;

export function signLiveToken(
  secret: string,
  url: string,
  profile: string,
  nowMs: number = Date.now(),
  nonce: string = randomBytes(8).toString("hex"),
): string {
  // Sorted keys, no spaces: Python writes json.dumps(..., separators=(",", ":"),
  // sort_keys=True) and the signature covers the encoded bytes.
  //
  // jti is what makes two tokens for the same page in the same second
  // different documents. Without it they are byte-identical, and single use
  // would refuse the second person to open that page in that second.
  const payload = JSON.stringify({
    exp: Math.floor(nowMs / 1000) + TOKEN_TTL_S,
    jti: nonce,
    profile,
    url,
  });
  const body = Buffer.from(payload, "utf8").toString("base64url");
  return `${body}.${createHmac("sha256", secret).update(body).digest("hex")}`;
}

/** The websocket the browser opens, straight to the service.
 *
 *  No token in the URL: uvicorn writes the full query string to its access
 *  log, and Railway keeps those, so a token there is a token on disk that can
 *  be replayed until it expires. It is sent as the socket's first message. */
export function liveSocketUrl(serviceUrl: string): string {
  const base = serviceUrl.replace(/\/+$/, "").replace(/^http/, "ws");
  return `${base}/api/devicepreview/live-session`;
}
